console.log ('app.js');
console.log ('Hola Bea');
console.log ('Bienvenidos a Git');
console.log ('Esta es una prueba');
console.log ('primer trabajo en GIT');
console.log ('ahora a ver que queda');
console.log ('vamos!');
console.log ('vamos!');
console.log ('vamos!');
console.log ('vamos!');
console.log ('vamos!');
console.log ('vamos!');
